### ISSUE TITLE
helper.env_file removes hash (#) at the end of an environment variable value in task definition

### ISSUE THREAD

**Issue by cekediz** [tongueroo/ufo#47]
Hi there. First of all, thanks for this awesome gem.

One of my environment variables looks like this:  `SOME_KEY=WYNL3g!EvjSLG&W#`  

The helper method will always remove the trailing `#`, so in the resulting task definition file, the variable always looks like this:
```
{
  "name": "SOME_KEY",
  "value": "WYNL3g!EvjSLG&W"
 }
```
Adding double or single quotes around the value doesn't help. Any suggestions?

**Comment by tongueroo** [comment]
@cekediz Thanks for pointing out the edge case bug. Issue is that ufo parses the `.env` files and strips out trailing comments. So you can add comments to the if you'd like.

Fixed in https://github.com/tongueroo/ufo/commit/6340e79103e386db9370f2822a5782728bc0a8fd 

Released in version 4.1.4 https://github.com/tongueroo/ufo/blob/master/CHANGELOG.md
