### ISSUE TITLE
UFO not using image for environment if you switch AWS profiles

### ISSUE THREAD

**Issue by joeyvmason** [tongueroo/ufo#51]
I'm trying to use UFO to deploy to different AWS accounts depending on the environment (e.g. staging / production). I'm also using ECR, so that means that the `image` field needs to be configurable because each AWS account has its own ECR registry. However, when setting the AWS profile, it doesn't seem to be using the correct variable.  

Here is an example `settings.yml` file

```
base:
   image: default/image

staging:
   image: new/image
   aws_profiles:
      - staging
```

If I set the AWS profile to `staging` (by setting `AWS_PROFILE` environment variable) and then call `ufo ship`, it still uses the base image, instead of the correct one for the staging environment.

**Comment by tongueroo** [comment]
@joeyvmason Interesting, the `.ufo/settings.yml` file you have should work. Support for this use case was added in #10 "Parameterized Image Name by Environment". Unsure why it's not working for you 🧐  Did some testing to double check that different images for different environments work.

## Test Setup

The test `.ufo/settings.yml` file:

```yaml
base:
  image: tongueroo/demo-ufo

development:

production:
  image: tongueroo/test-ufo
  cluster: production
  aws_profiles:
    - bolt-demo
```

## AWS_PROFILE=bolt-tung

bolt-tung is a separate AWS account with a separate AWS_PROFILE. This maps to the default base image value of `tongueroo/demo-ufo` in `.ufo/settings.yml` because the `bolt-tung` profile is not set in the settings.yml file.  Run a `ufo ship` and inspected the output to verify that different images are being used for different environments.

    $ AWS_PROFILE=bolt-tung ufo ship
    Building docker image with:
      docker build -t tongueroo/demo-ufo:ufo-2018-10-21T11-31-55-eb0789a -f Dockerfile .
    ...
    => docker push tongueroo/demo-ufo:ufo-2018-10-21T11-31-55-eb0789a
    ...
    Docker push took 3s.
    Building Task Definitions...
    Generating Task Definitions:
      .ufo/output/demo-web.json
    Task Definitions built in .ufo/output
    Equivalent aws cli command:
      aws ecs register-task-definition --cli-input-json file://.ufo/output/demo-web.json
    ...
    $ grep image .ufo/output/demo-web.json
          "image": "tongueroo/demo-ufo:ufo-2018-10-21T11-33-22-eb0789a",
    $

## AWS_PROFILE=bolt-demo

bolt-demo is also a separate AWS account.  This maps to the `production` environment in this case because `aws_profiles` contains `bolt-demo` as a value underneath that section.

    $ AWS_PROFILE=bolt-demo ufo ship
    Building docker image with:
      docker build -t tongueroo/test-ufo:ufo-2018-10-21T11-35-20-eb0789a -f Dockerfile .
    ...
    Building Task Definitions...
    Generating Task Definitions:
      .ufo/output/demo-web.json
    ...
    Equivalent aws cli command:
      aws ecs register-task-definition --cli-input-json file://.ufo/output/demo-web.json
    demo-web task definition registered.
    ...
    $ grep image .ufo/output/demo-web.json
          "image": "tongueroo/test-ufo:ufo-2018-10-21T11-35-20-eb0789a",
    $

I've filtered out the output for debugging. From the output it looks like the image name being respected.

AWS_PROFILE | environment | base image | timestamped image
--- | --- | --- | ---
bolt-tung | development | tongueroo/demo-ufo | tongueroo/demo-ufo:ufo-2018-10-21T11-31-55-eb0789a
bolt-demo | production | tongueroo/test-ufo | tongueroo/test-ufo:ufo-2018-10-21T11-35-20-eb0789a

So I think this works. Hope this helps.  Closing out but feel free to comment additionally.
