### ISSUE TITLE
Automatic daemon service creation

### ISSUE THREAD

**Issue by cekediz** [tongueroo/ufo#54]
Hi!
I understand that ufo will automatically create a new service if none exists yet -- is it possible for me to pre-define the scheduling strategy i.e. REPLICA vs DAEMON anywhere in the ufo configuration?

Thanks.

**Comment by tongueroo** [comment]
@cekediz Hi there! Good question. 

Dug into this. While it is possible to override pretty much any of the CloudFormation resource properties by using a custom cfn settings file. Details here [Ufo Cfn Settings](http://ufoships.com/docs/settings-cfn/). This is not ideal because it would mean you will have to use the same DAEMON scheduling strategy for all your ufo services, ie: web, worker, clock, etc.

So went ahead and added support for this feature. You can now specify the scheduling strategy as a part of the `ufo ship` command. Example:

    ufo ship --scheduling-strategy daemon

The CLI reference docs has also been updated with details: http://ufoships.com/reference/ufo-ship/

Released in v4.1.7 [CHANGELOG](https://github.com/tongueroo/ufo/blob/master/CHANGELOG.md)

Closing this out.
