### ISSUE TITLE
Support for ssm parameter? IAM?

### ISSUE THREAD

**Issue by ptqa** [tongueroo/ufo#63]
Hi, cool project!

I have few questions:
1. How secrets are supposed to be managed? Currently I'm using SSM (see https://aws.amazon.com/blogs/mt/the-right-way-to-store-secrets-using-parameter-store/), but I can't find anything about secrets in docs/repo.
2. What about IAM roles for task execution & execution role? I found something for fargate, but what about EC2 launch type?

**Comment by tongueroo** [comment]
> RE: 1. How secrets are supposed to be managed? Currently I'm using SSM (see https://aws.amazon.com/blogs/mt/the-right-way-to-store-secrets-using-parameter-store/), but I can't find anything about secrets in docs/repo.

Right now, ufo doesn't natively support parameter-store. You can store your secrets in `.env` files and then use the `env_file` [helper](http://ufoships.com/docs/helpers/) to load it. Then store the .env files in s3. 

Also, have used a script that loads the secrets from parameter store based on some conventions. The script is pretty old, as it uses periods instead of slashes to separate the namespace. It was written before AWS introduced the namespace concept with slashes. Here's the [bin/secrets.rb](https://gist.github.com/tongueroo/d211cc2cc714f2f409a0514d88d72b44)  Will consider pull requests for this. 👌

RE: 2. What about IAM roles for task execution & execution role? I found something for fargate, but what about EC2 launch type?

Yup, so IAM roles are configurable by changing your task definition in `.ufo/templates`.  Here are the templates that [ufo init](http://ufoships.com/reference/ufo-init/) uses 

* EC2: https://github.com/tongueroo/ufo/blob/master/lib/template/.ufo/templates/main.json.erb
* Fargate: https://github.com/tongueroo/ufo/blob/master/lib/template/.ufo/templates/fargate.json.erb

The starter Fargate template has an `executionRoleArn` example and EC2 does not. You can just add it to the EC2 template though. This is one of the reasons I wrote ufo.  You have full control over the ECS task definition. 👍
