### ISSUE TITLE
ELB/Service and other naming conventions

### ISSUE THREAD

**Issue by kierachell** [tongueroo/ufo#67]
Currently some of there resources get their names randomly suffixed  which makes it hard to use and generates problematic domain names for ELBs.

![screen shot 2019-02-15 at 2 44 11 pm](https://user-images.githubusercontent.com/18075411/52886045-5245ad00-3130-11e9-8645-e17b85663a93.png)
![screen shot 2019-02-15 at 2 44 20 pm](https://user-images.githubusercontent.com/18075411/52886046-5245ad00-3130-11e9-8a6c-b76818cc23b1.png)

* A similar hack for docker image tagging `${UFO_DOCKER_BUILD_OPTIONS/:*/real_tag_that_i_want_instead_of_what_ufo_generates}` is already a lot of work

### Request

* It would be nice to customize/template these and other generated names in a more human-readable form

**Comment by tongueroo** [comment]
Sure. Random suffixes get added since ufo uses CloudFormation to build the ECS Service and ELBs. Some thoughts on this are here: http://ufoships.com/docs/why-cloudformation/

Even with CloudFormation, had also attempted to use pretty names. There's still an undocumented flag to do this `STATIC_NAME`

https://github.com/tongueroo/ufo/blob/fa6ca2eb75c9aa1c745f78fc24ad66d69628acff/lib/ufo/template_scope.rb#L113-L120

When using the flag, it will name some of the components with pretty names. TBH though, wouldn't recommend using it. Sometimes updating the ECS Service requires replacement of the entire service. CloudFormation handles this fine when it's allowed to add a random suffix to the ECS service name, but has issues when a static or pretty name is defined. Tested enough where it didn't seem worth it.

Think a better recommendation, at least for web tiers, is to use [Route 53](http://ufoships.com/docs/route53-support/) and add a pretty DNS entry that points to the ELB.  For worker tiers, think there are less issues down the line to let CloudFormation add the random suffix.
