### ISSUE TITLE
Allow referencing existing Docker image from ECR

### ISSUE THREAD

**Issue by kierachell** [tongueroo/ufo#68]
To create truly reliable deployments it should be possible to deploy a service and reference a Docker image from ECR instead of rebuilding/pushing it each time.

e.g. it could be done via `--tag` flag so that I can deploy my own `image-name:deployed` tag.

This will also allow UFO to run in Docker because it won't require a docker daemon running since it won't reference any docker commands.

**Comment by tongueroo** [comment]
Maybe not ideal, but there are current ways to use a specific tag. The ECS task definition have the tag in there instead of using `@image` variable: http://ufoships.com/docs/tutorial-ufo-tasks-build/ 

Also, can deploy things in pieces and skip the docker build stage.  Docs here: http://ufoships.com/docs/run-in-pieces/

Can consider PRs for this though.
